import React from 'react';
import { CalculationResults, SystemConfig, Room } from '../types';
import { Download, FileText } from 'lucide-react';

interface BOMProps {
  results: CalculationResults;
  config: SystemConfig;
  rooms: Room[];
}

export function BOM({ results, config, rooms }: BOMProps) {
  
  const generatePDF = () => {
    window.print();
  };

  // Rough estimates for BOM
  const panelWattage = 400;
  const numPanels = Math.ceil(results.requiredPvArraySizeW / panelWattage);
  
  const batteryVoltage = 12;
  const batteryAh = 200;
  const numBatteries = Math.ceil(results.requiredBatteryCapacityAh / batteryAh);

  const inverterKw = Math.ceil(results.requiredInverterSizeW / 1000);

  return (
    <div className="bg-white dark:bg-[#181818] rounded-3xl transition-colors duration-300 p-8 lg:p-12 mt-12">
      <div className="print:hidden flex flex-col sm:flex-row items-start sm:items-center justify-between pb-8 gap-4 transition-colors">
        <div className="text-2xl font-light text-slate-900 dark:text-white flex items-center gap-4 transition-colors">
          Bill of Materials
        </div>
        <button onClick={generatePDF} className="bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-900 dark:text-white transition-colors py-3 px-6 text-xs font-semibold uppercase tracking-widest flex items-center gap-3 rounded-xl">
          <Download className="w-4 h-4" /> Download PDF
        </button>
      </div>
      <div id="bom-content">
        
        <div className="mb-12 border-b border-slate-100 dark:border-neutral-800 pb-8 transition-colors">
          <h2 className="text-3xl font-light text-slate-900 dark:text-white mb-2 tracking-tight transition-colors">System Specification List</h2>
          <p className="text-xs font-medium text-amber-500 uppercase tracking-widest">Generated by SOLARIS Architect Engine</p>
        </div>

        <div className="space-y-16">
          <div>
            <h3 className="text-xs font-medium text-slate-400 dark:text-neutral-500 uppercase tracking-widest mb-6 flex items-center gap-4 transition-colors">
              <span className="w-6 h-6 border rounded-full border-slate-200 dark:border-neutral-700 text-slate-400 flex items-center justify-center text-xs transition-colors">1</span> 
              Solar Array
            </h3>
            <div className="overflow-x-auto w-full -mx-6 sm:mx-0 px-6 sm:px-0 scrollbar-hide">
              <table className="w-full text-sm min-w-[500px]">
                <tbody>
                  <tr className="border-b border-slate-100 dark:border-neutral-800/50 hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                    <td className="py-4 px-4 text-slate-500 dark:text-neutral-400 uppercase tracking-wider text-xs whitespace-nowrap">Photovoltaic Panels</td>
                    <td className="py-4 px-4 font-mono text-right font-medium text-slate-900 dark:text-white whitespace-nowrap">{numPanels}x</td>
                    <td className="py-4 px-4 text-right text-slate-500 dark:text-neutral-500 font-mono text-xs uppercase tracking-wider whitespace-nowrap">{panelWattage}W Monocrystalline</td>
                  </tr>
                  <tr className="border-b border-transparent hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                    <td className="py-6 px-4 text-slate-900 dark:text-white font-medium uppercase tracking-wider text-[11px] whitespace-nowrap">Total Array Capacity</td>
                    <td className="py-6 px-4 font-mono text-right"></td>
                    <td className="py-6 px-4 text-right font-mono font-medium text-amber-500 text-xl whitespace-nowrap">{(numPanels * panelWattage / 1000).toFixed(2)} kW</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div>
            <h3 className="text-xs font-medium text-slate-400 dark:text-neutral-500 uppercase tracking-widest mb-6 flex items-center gap-4 transition-colors">
              <span className="w-6 h-6 border rounded-full border-slate-200 dark:border-neutral-700 text-slate-400 flex items-center justify-center text-xs transition-colors">2</span> 
              Energy Storage
            </h3>
            <div className="overflow-x-auto w-full -mx-6 sm:mx-0 px-6 sm:px-0 scrollbar-hide">
              <table className="w-full text-sm min-w-[500px]">
                <tbody>
                  <tr className="border-b border-slate-100 dark:border-neutral-800/50 hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                    <td className="py-4 px-4 text-slate-500 dark:text-neutral-400 uppercase tracking-wider text-xs whitespace-nowrap">Deep Cycle Batteries</td>
                    <td className="py-4 px-4 font-mono text-right font-medium text-slate-900 dark:text-white whitespace-nowrap">{numBatteries}x</td>
                    <td className="py-4 px-4 text-right text-slate-500 dark:text-neutral-500 font-mono text-xs uppercase tracking-wider whitespace-nowrap">{batteryVoltage}V {batteryAh}Ah</td>
                  </tr>
                  <tr className="border-b border-transparent hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                    <td className="py-6 px-4 text-slate-900 dark:text-white font-medium uppercase tracking-wider text-[11px] whitespace-nowrap">Total Storage Capacity</td>
                    <td className="py-6 px-4 font-mono text-right"></td>
                    <td className="py-6 px-4 text-right font-mono font-medium text-amber-500 text-xl whitespace-nowrap">{(numBatteries * batteryVoltage * batteryAh / 1000).toFixed(2)} kWh</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div>
            <h3 className="text-xs font-medium text-slate-400 dark:text-neutral-500 uppercase tracking-widest mb-6 flex items-center gap-4 transition-colors">
              <span className="w-6 h-6 border rounded-full border-slate-200 dark:border-neutral-700 text-slate-400 flex items-center justify-center text-xs transition-colors">3</span> 
              Power Conversion
            </h3>
            <div className="overflow-x-auto w-full -mx-6 sm:mx-0 px-6 sm:px-0 scrollbar-hide">
              <table className="w-full text-sm min-w-[500px]">
                <tbody>
                  <tr className="border-b border-slate-100 dark:border-neutral-800/50 hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                    <td className="py-4 px-4 text-slate-500 dark:text-neutral-400 uppercase tracking-wider text-xs whitespace-nowrap">Hybrid Inverter/Charger</td>
                    <td className="py-4 px-4 font-mono text-right font-medium text-slate-900 dark:text-white whitespace-nowrap">1x</td>
                    <td className="py-4 px-4 text-right text-slate-500 dark:text-neutral-500 font-mono text-xs uppercase tracking-wider whitespace-nowrap">{inverterKw} kW ({config.systemVoltage}V DC)</td>
                  </tr>
                  <tr className="border-b border-transparent hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                    <td className="py-4 px-4 text-slate-500 dark:text-neutral-400 uppercase tracking-wider text-[11px] whitespace-nowrap">Charge Controller</td>
                    <td className="py-4 px-4 font-mono text-right font-medium text-slate-900 dark:text-white whitespace-nowrap">1x</td>
                    <td className="py-4 px-4 text-right text-slate-500 dark:text-neutral-500 font-mono text-xs uppercase tracking-wider whitespace-nowrap">MPPT (Matched to Array)</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          
          <div>
            <h3 className="text-xs font-medium text-slate-400 dark:text-neutral-500 uppercase tracking-widest mb-6 flex items-center gap-4 transition-colors">
              <span className="w-6 h-6 border rounded-full border-slate-200 dark:border-neutral-700 text-slate-400 flex items-center justify-center text-xs transition-colors">4</span> 
              Load Specification
            </h3>
            <div className="overflow-x-auto w-full -mx-6 sm:mx-0 px-6 sm:px-0 scrollbar-hide">
              <table className="w-full text-sm min-w-[600px]">
                <thead>
                  <tr className="border-b border-slate-200 dark:border-neutral-700 text-[10px] uppercase tracking-wider text-slate-400 text-left">
                    <th className="py-4 px-4 font-medium whitespace-nowrap">Appliance</th>
                    <th className="py-4 px-4 font-medium text-center whitespace-nowrap">Qty</th>
                    <th className="py-4 px-4 font-medium text-right whitespace-nowrap">Power (W)</th>
                    <th className="py-4 px-4 font-medium text-right whitespace-nowrap">Hours/Day</th>
                    <th className="py-4 px-4 font-medium text-right whitespace-nowrap">Daily Wh</th>
                  </tr>
                </thead>
                <tbody>
                  {rooms.flatMap(room => 
                    room.appliances.filter(a => a.quantity > 0 && a.continuousWatts > 0 && a.hoursPerDay > 0).map(app => (
                      <tr key={`${room.id}-${app.id}`} className="border-b border-slate-100 dark:border-neutral-800/50 hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                        <td className="py-4 px-4">
                           <div className="font-medium text-slate-900 dark:text-white text-sm break-words max-w-[200px]">{app.name}</div>
                           <div className="text-[10px] uppercase tracking-widest text-slate-400 mt-1 truncate max-w-[200px]">{room.name}</div>
                        </td>
                        <td className="py-4 px-4 font-mono text-center text-slate-900 dark:text-white whitespace-nowrap">{app.quantity}</td>
                        <td className="py-4 px-4 font-mono text-right text-slate-900 dark:text-white whitespace-nowrap">{app.continuousWatts}W</td>
                        <td className="py-4 px-4 font-mono text-right text-slate-900 dark:text-white whitespace-nowrap">{app.hoursPerDay}h</td>
                        <td className="py-4 px-4 font-mono text-right font-medium text-slate-900 dark:text-white whitespace-nowrap">
                          {(app.quantity * app.continuousWatts * app.hoursPerDay * (app.dutyCycle ?? 1)).toLocaleString()} Wh
                        </td>
                      </tr>
                    ))
                  )}
                  <tr className="border-b border-transparent hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                    <td colSpan={4} className="py-6 px-4 text-slate-900 dark:text-white font-medium uppercase tracking-wider text-[11px] whitespace-nowrap">Total Daily Load</td>
                    <td className="py-6 px-4 text-right font-mono font-medium text-amber-500 text-xl whitespace-nowrap">{(results.totalDailyLoadWh / 1000).toLocaleString(undefined, {minimumFractionDigits: 1, maximumFractionDigits: 2})} kWh</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          
          <div className="mt-16 p-8 bg-slate-50 dark:bg-white/5 rounded-2xl text-[10px] text-slate-500 dark:text-neutral-400 leading-relaxed uppercase tracking-widest">
            <p><strong className="text-slate-900 dark:text-white font-medium block mb-2">Disclaimer</strong> This Bill of Materials is an engineering approximation based on user-provided load profiles and standard industry assumptions. A certified solar installer must verify all calculations, local code compliance, and specific hardware prior to purchase.</p>
          </div>
        </div>

      </div>
    </div>
  );
}
