import React from 'react';
import { CalculationResults, SystemConfig, Room } from '../types';
import { Download, FileText } from 'lucide-react';

interface BOMProps {
  results: CalculationResults;
  config: SystemConfig;
  rooms: Room[];
}

export function BOM({ results, config, rooms }: BOMProps) {
  
  const generatePDF = () => {
    window.print();
  };

  // Rough estimates for BOM
  const panelWattage = 400;
  const numPanels = Math.ceil(results.requiredPvArraySizeW / panelWattage);
  
  const batteryVoltage = 12;
  const batteryAh = 200;
  const numBatteries = Math.ceil(results.requiredBatteryCapacityAh / batteryAh);

  const inverterKw = Math.ceil(results.requiredInverterSizeW / 1000);

  return (
    <div className="border border-slate-200/80 dark:border-white/5 bg-white dark:bg-[#181818] rounded-3xl overflow-hidden shadow-[0_8px_30px_rgb(0,0,0,0.06)] dark:shadow-none transition-colors duration-300">
      <div className="print:hidden flex flex-col sm:flex-row items-start sm:items-center justify-between border-b border-slate-100 dark:border-neutral-800 py-6 px-8 gap-4 transition-colors">
        <div className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-4 uppercase tracking-[0.1em] transition-colors">
          <div className="w-10 h-10 rounded-xl border border-slate-200 dark:border-neutral-800 flex items-center justify-center bg-slate-50 dark:bg-transparent shadow-sm dark:shadow-none transition-colors">
            <FileText className="w-5 h-5 text-slate-500 dark:text-neutral-500" />
          </div>
          Bill of Materials
        </div>
        <button onClick={generatePDF} className="border border-slate-200 dark:border-neutral-700 text-slate-500 dark:text-neutral-400 hover:text-slate-900 hover:border-amber-600 hover:bg-slate-50 dark:hover:text-white dark:hover:border-[#FFE600] transition-colors py-3 px-6 text-[10px] font-bold uppercase tracking-[0.15em] flex items-center gap-3 bg-white dark:bg-transparent rounded-xl shadow-sm dark:shadow-none">
          <Download className="w-4 h-4" /> Download PDF
        </button>
      </div>
      <div className="p-10" id="bom-content">
        
        <div className="mb-8 sm:mb-12 border-b border-slate-200 dark:border-neutral-800 pb-6 sm:pb-8 transition-colors">
          <h2 className="text-xl sm:text-2xl md:text-3xl font-bold text-slate-900 dark:text-white mb-2 sm:mb-3 tracking-tight transition-colors">System Specification List</h2>
          <p className="text-[9px] sm:text-[10px] font-bold text-amber-600 dark:text-[#FFE600] uppercase tracking-[0.2em]">Generated by SOLARIS Architect Engine</p>
        </div>

        <div className="space-y-12">
          <div>
            <h3 className="text-[10px] font-bold text-slate-500 dark:text-neutral-500 uppercase tracking-[0.2em] mb-4 border-b border-slate-200 dark:border-neutral-800 pb-2 flex items-center gap-3 transition-colors">
              <span className="w-5 h-5 border border-slate-300 dark:border-neutral-700 text-slate-500 dark:text-neutral-400 flex items-center justify-center text-[9px] transition-colors">1</span> 
              Solar Array
            </h3>
            <div className="overflow-x-auto w-full -mx-4 px-4 sm:mx-0 sm:px-0">
              <table className="w-full text-xs sm:text-sm">
                <tbody>
                  <tr className="border-b border-slate-200 dark:border-neutral-800/50 hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-3 sm:py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[9px] sm:text-[10px]">Photovoltaic Panels</td>
                    <td className="py-4 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">{numPanels}x</td>
                    <td className="py-4 px-2 text-right text-slate-500 dark:text-neutral-500 font-mono text-[10px] uppercase tracking-wider">{panelWattage}W Monocrystalline</td>
                  </tr>
                  <tr className="border-b border-transparent hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[10px]">Total Array Capacity</td>
                    <td className="py-4 px-2 font-mono text-right"></td>
                    <td className="py-4 px-2 text-right font-mono font-bold text-amber-600 dark:text-[#FFE600] tracking-widest text-lg">{(numPanels * panelWattage / 1000).toFixed(2)} kW</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div>
            <h3 className="text-[10px] font-bold text-slate-500 dark:text-neutral-500 uppercase tracking-[0.2em] mb-4 border-b border-slate-200 dark:border-neutral-800 pb-2 flex items-center gap-3 transition-colors">
              <span className="w-5 h-5 border border-slate-300 dark:border-neutral-700 text-slate-500 dark:text-neutral-400 flex items-center justify-center text-[9px] transition-colors">2</span> 
              Energy Storage
            </h3>
            <div className="overflow-x-auto w-full -mx-4 px-4 sm:mx-0 sm:px-0">
              <table className="w-full text-xs sm:text-sm">
                <tbody>
                  <tr className="border-b border-slate-200 dark:border-neutral-800/50 hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-3 sm:py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[9px] sm:text-[10px]">Deep Cycle Batteries</td>
                    <td className="py-4 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">{numBatteries}x</td>
                    <td className="py-4 px-2 text-right text-slate-500 dark:text-neutral-500 font-mono text-[10px] uppercase tracking-wider">{batteryVoltage}V {batteryAh}Ah</td>
                  </tr>
                  <tr className="border-b border-transparent hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[10px]">Total Storage Capacity</td>
                    <td className="py-4 px-2 font-mono text-right"></td>
                    <td className="py-4 px-2 text-right font-mono font-bold tracking-widest text-amber-600 dark:text-[#FFE600] text-lg">{(numBatteries * batteryVoltage * batteryAh / 1000).toFixed(2)} kWh</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div>
            <h3 className="text-[10px] font-bold text-slate-500 dark:text-neutral-500 uppercase tracking-[0.2em] mb-4 border-b border-slate-200 dark:border-neutral-800 pb-2 flex items-center gap-3 transition-colors">
              <span className="w-5 h-5 border border-slate-300 dark:border-neutral-700 text-slate-500 dark:text-neutral-400 flex items-center justify-center text-[9px] transition-colors">3</span> 
              Power Conversion
            </h3>
            <div className="overflow-x-auto w-full -mx-4 px-4 sm:mx-0 sm:px-0">
              <table className="w-full text-xs sm:text-sm">
                <tbody>
                  <tr className="border-b border-slate-200 dark:border-neutral-800/50 hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-3 sm:py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[9px] sm:text-[10px]">Hybrid Inverter/Charger</td>
                    <td className="py-4 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">1x</td>
                    <td className="py-4 px-2 text-right text-slate-500 dark:text-neutral-500 font-mono text-[10px] uppercase tracking-wider">{inverterKw} kW ({config.systemVoltage}V DC)</td>
                  </tr>
                  <tr className="border-b border-transparent hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[10px]">Charge Controller</td>
                    <td className="py-4 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">1x</td>
                    <td className="py-4 px-2 text-right text-slate-500 dark:text-neutral-500 font-mono text-[10px] uppercase tracking-wider">MPPT (Matched to Array)</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          
          <div>
            <h3 className="text-[10px] font-bold text-slate-500 dark:text-neutral-500 uppercase tracking-[0.2em] mb-4 border-b border-slate-200 dark:border-neutral-800 pb-2 flex items-center gap-3 transition-colors">
              <span className="w-5 h-5 border border-slate-300 dark:border-neutral-700 text-slate-500 dark:text-neutral-400 flex items-center justify-center text-[9px] transition-colors">4</span> 
              Financial Investment Estimate
            </h3>
            <div className="overflow-x-auto w-full -mx-4 px-4 sm:mx-0 sm:px-0">
              <table className="w-full text-xs sm:text-sm">
                <tbody>
                  <tr className="border-b border-slate-200 dark:border-neutral-800/50 hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-3 sm:py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[9px] sm:text-[10px]">Solar PV Array</td>
                    <td className="py-4 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">₦ {results.estimatedPvCostNGN.toLocaleString('en-US', {maximumFractionDigits:0})}</td>
                  </tr>
                  <tr className="border-b border-slate-200 dark:border-neutral-800/50 hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-3 sm:py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[9px] sm:text-[10px]">Energy Storage (Batteries)</td>
                    <td className="py-4 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">₦ {results.estimatedBatteryCostNGN.toLocaleString('en-US', {maximumFractionDigits:0})}</td>
                  </tr>
                  <tr className="border-b border-slate-200 dark:border-neutral-800/50 hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-3 sm:py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[9px] sm:text-[10px]">Power Conversion (Inverter/MPPT)</td>
                    <td className="py-4 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">₦ {results.estimatedInverterCostNGN.toLocaleString('en-US', {maximumFractionDigits:0})}</td>
                  </tr>
                  <tr className="border-b border-slate-200 dark:border-neutral-800/50 hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-3 sm:py-4 px-2 text-slate-500 dark:text-neutral-400 font-bold uppercase tracking-wider text-[9px] sm:text-[10px]">Installation & Accessories (20%)</td>
                    <td className="py-4 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">₦ {((results.estimatedPvCostNGN + results.estimatedInverterCostNGN + results.estimatedBatteryCostNGN) * 0.2).toLocaleString('en-US', {maximumFractionDigits:0})}</td>
                  </tr>
                  <tr className="border-b border-transparent hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td className="py-4 px-2 text-slate-900 dark:text-white font-extrabold uppercase tracking-wider text-[11px] sm:text-[12px]">Total Estimated Investment</td>
                    <td className="py-4 px-2 text-right font-mono font-bold tracking-widest text-amber-600 dark:text-[#FFE600] text-xl">₦ {(results.totalEstimatedCostNGN).toLocaleString('en-US', {maximumFractionDigits:0})}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          
          <div>
            <h3 className="text-[10px] font-bold text-slate-500 dark:text-neutral-500 uppercase tracking-[0.2em] mb-4 border-b border-slate-200 dark:border-neutral-800 pb-2 flex items-center gap-3 transition-colors">
              <span className="w-5 h-5 border border-slate-300 dark:border-neutral-700 text-slate-500 dark:text-neutral-400 flex items-center justify-center text-[9px] transition-colors">5</span> 
              Load Specification
            </h3>
            <div className="overflow-x-auto w-full -mx-4 px-4 sm:mx-0 sm:px-0">
              <table className="w-full text-xs sm:text-sm">
                <thead>
                  <tr className="border-b border-slate-200 dark:border-neutral-800 text-[9px] uppercase tracking-wider text-slate-500 text-left">
                    <th className="py-2 px-2 font-bold">Appliance</th>
                    <th className="py-2 px-2 font-bold text-center">Qty</th>
                    <th className="py-2 px-2 font-bold text-right">Power (W)</th>
                    <th className="py-2 px-2 font-bold text-right">Hours/Day</th>
                    <th className="py-2 px-2 font-bold text-right">Daily Wh</th>
                  </tr>
                </thead>
                <tbody>
                  {rooms.flatMap(room => 
                    room.appliances.filter(a => a.quantity > 0 && a.continuousWatts > 0 && a.hoursPerDay > 0).map(app => (
                      <tr key={`${room.id}-${app.id}`} className="border-b border-slate-200/50 dark:border-neutral-800/50 hover:bg-white dark:hover:bg-white/5 transition-colors">
                        <td className="py-3 px-2">
                           <div className="font-bold text-slate-900 dark:text-white text-[10px]">{app.name}</div>
                           <div className="text-[9px] text-slate-500">{room.name}</div>
                        </td>
                        <td className="py-3 px-2 font-mono text-center text-slate-900 dark:text-white">{app.quantity}</td>
                        <td className="py-3 px-2 font-mono text-right text-slate-900 dark:text-white">{app.continuousWatts}W</td>
                        <td className="py-3 px-2 font-mono text-right text-slate-900 dark:text-white">{app.hoursPerDay}h</td>
                        <td className="py-3 px-2 font-mono text-right font-bold text-slate-900 dark:text-white">
                          {(app.quantity * app.continuousWatts * app.hoursPerDay * (app.dutyCycle ?? 1)).toLocaleString()} Wh
                        </td>
                      </tr>
                    ))
                  )}
                  <tr className="border-b border-transparent hover:bg-white dark:hover:bg-white/5 transition-colors">
                    <td colSpan={4} className="py-4 px-2 text-slate-900 dark:text-white font-extrabold uppercase tracking-wider text-[11px] sm:text-[12px]">Total Daily Load</td>
                    <td className="py-4 px-2 text-right font-mono font-bold tracking-widest text-amber-600 dark:text-[#FFE600] text-lg">{(results.totalDailyLoadWh / 1000).toLocaleString(undefined, {minimumFractionDigits: 1, maximumFractionDigits: 2})} kWh</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          
          <div className="mt-12 p-8 border border-slate-200/80 dark:border-neutral-800 bg-slate-50 dark:bg-black/50 text-[10px] text-slate-500 dark:text-neutral-500 leading-relaxed uppercase tracking-[0.1em] transition-colors rounded-2xl">
            <p><strong className="text-slate-900 dark:text-white transition-colors">Disclaimer:</strong> This Bill of Materials and Financial Estimate is an engineering approximation based on user-provided load profiles and standard industry assumptions. Component prices fluctuate based on market availability, brand selection, and battery chemistry (e.g. Lithium vs Lead Acid). A certified solar installer must verify all calculations, local code compliance, and specific hardware prior to purchase.</p>
          </div>
        </div>

      </div>
    </div>
  );
}
